export const TRAINING_BRAIN_REASON_CODES = Object.freeze({
  GOAL_RECOGNIZED: 'GOAL_RECOGNIZED',
  BYPASS_UNSUPPORTED_PATH: 'BYPASS_UNSUPPORTED_PATH',
  CANDIDATES_GENERATED: 'CANDIDATES_GENERATED',
  CANDIDATE_SELECTED: 'CANDIDATE_SELECTED',
  PROGRAM_ENGINE_COMPATIBLE: 'PROGRAM_ENGINE_COMPATIBLE',
  FREQUENCY_FROM_DAYS: 'FREQUENCY_FROM_DAYS',
  DURATION_CAPACITY_FROM_SESSION_LENGTH: 'DURATION_CAPACITY_FROM_SESSION_LENGTH',
  GOAL_WORKLOAD_DEFAULT: 'GOAL_WORKLOAD_DEFAULT',
  EXPERIENCE_COMPLEXITY: 'EXPERIENCE_COMPLEXITY',
  RECOVERY_CONSERVATIVE: 'RECOVERY_CONSERVATIVE',
  RECOVERY_PERFORMANCE: 'RECOVERY_PERFORMANCE',
  RECOVERY_BALANCED: 'RECOVERY_BALANCED',
  TRAINING_FOCUS_STRENGTH: 'TRAINING_FOCUS_STRENGTH',
  TRAINING_FOCUS_HYPERTROPHY: 'TRAINING_FOCUS_HYPERTROPHY',
  TRAINING_FOCUS_GOAL_PRECEDENCE: 'TRAINING_FOCUS_GOAL_PRECEDENCE',
  HARD_CONSTRAINTS_RECORDED: 'HARD_CONSTRAINTS_RECORDED',
  SEX_AWARE_NEUTRAL_FOUNDATION: 'SEX_AWARE_NEUTRAL_FOUNDATION',
  CYCLE_CONTEXT_METADATA_ONLY: 'CYCLE_CONTEXT_METADATA_ONLY',
  BODY_TYPE_INFORMATIONAL_ONLY: 'BODY_TYPE_INFORMATIONAL_ONLY',
  REFERENCE_EVIDENCE_EVALUATED: 'REFERENCE_EVIDENCE_EVALUATED',
  NO_COMPATIBLE_CANDIDATE: 'NO_COMPATIBLE_CANDIDATE',
});

export const TRAINING_BRAIN_WARNING_CODES = Object.freeze({
  EQUIPMENT_INFORMATION_MISSING: 'EQUIPMENT_INFORMATION_MISSING',
  EQUIPMENT_INFORMATION_AMBIGUOUS: 'EQUIPMENT_INFORMATION_AMBIGUOUS',
  OPTIONAL_GENDER_MISSING: 'OPTIONAL_GENDER_MISSING',
  OPTIONAL_TRAINING_FOCUS_MISSING: 'OPTIONAL_TRAINING_FOCUS_MISSING',
  OPTIONAL_RECOVERY_STRATEGY_MISSING: 'OPTIONAL_RECOVERY_STRATEGY_MISSING',
  POWERLIFTING_CONSTRAINT_CONFLICT: 'POWERLIFTING_CONSTRAINT_CONFLICT',
  POWERLIFTING_PRIMARY_MOVEMENT_CONFLICT: 'POWERLIFTING_PRIMARY_MOVEMENT_CONFLICT',
  NO_PROGRAM_ENGINE_COMPATIBLE_STRATEGY: 'NO_PROGRAM_ENGINE_COMPATIBLE_STRATEGY',
});

export const ALL_TRAINING_BRAIN_REASON_CODES = Object.freeze(
  Object.values(TRAINING_BRAIN_REASON_CODES),
);

export const ALL_TRAINING_BRAIN_WARNING_CODES = Object.freeze(
  Object.values(TRAINING_BRAIN_WARNING_CODES),
);

export const reason = (decision, code, inputs = {}, message = null) => ({
  decision,
  code,
  inputs,
  ...(message ? { message } : {}),
});

export const warning = (code, inputs = {}, message = null) => ({
  code,
  inputs,
  ...(message ? { message } : {}),
});
