export const NOTIFICATION_TYPES = Object.freeze({
  WORKOUT_REMINDER: 'WORKOUT_REMINDER',
  RECOVERY_READY: 'RECOVERY_READY',
  PLAN_UPDATED: 'PLAN_UPDATED',
  COACH_MESSAGE: 'COACH_MESSAGE',
  MISSED_WORKOUT: 'MISSED_WORKOUT',
  STREAK_PROTECTION: 'STREAK_PROTECTION',
  CHALLENGE_INVITATION: 'CHALLENGE_INVITATION',
  SUBSCRIPTION_REMINDER: 'SUBSCRIPTION_REMINDER',
  ONBOARDING_REMINDER: 'ONBOARDING_REMINDER',
  SHOP_DISCOUNT: 'SHOP_DISCOUNT',
  FRIEND_INVITATION: 'FRIEND_INVITATION',
  SOCIAL_ACTIVITY: 'SOCIAL_ACTIVITY',
  NEW_BOOK: 'NEW_BOOK',
});

export const NOTIFICATION_CATEGORIES = Object.freeze({
  TRAINING: 'training',
  COACH_MESSAGES: 'coach_messages',
  CHALLENGES: 'challenges',
  SUBSCRIPTION: 'subscription',
  SHOP: 'shop',
  SOCIAL: 'social',
  CONTENT: 'content',
  GYM: 'gym',
  SYSTEM: 'system',
});

export const TYPE_TO_CATEGORY = Object.freeze({
  [NOTIFICATION_TYPES.WORKOUT_REMINDER]: NOTIFICATION_CATEGORIES.TRAINING,
  [NOTIFICATION_TYPES.RECOVERY_READY]: NOTIFICATION_CATEGORIES.TRAINING,
  [NOTIFICATION_TYPES.PLAN_UPDATED]: NOTIFICATION_CATEGORIES.TRAINING,
  [NOTIFICATION_TYPES.COACH_MESSAGE]: NOTIFICATION_CATEGORIES.COACH_MESSAGES,
  [NOTIFICATION_TYPES.MISSED_WORKOUT]: NOTIFICATION_CATEGORIES.TRAINING,
  [NOTIFICATION_TYPES.STREAK_PROTECTION]: NOTIFICATION_CATEGORIES.TRAINING,
  [NOTIFICATION_TYPES.CHALLENGE_INVITATION]: NOTIFICATION_CATEGORIES.CHALLENGES,
  [NOTIFICATION_TYPES.SUBSCRIPTION_REMINDER]: NOTIFICATION_CATEGORIES.SUBSCRIPTION,
  [NOTIFICATION_TYPES.ONBOARDING_REMINDER]: NOTIFICATION_CATEGORIES.TRAINING,
  [NOTIFICATION_TYPES.SHOP_DISCOUNT]: NOTIFICATION_CATEGORIES.SHOP,
  [NOTIFICATION_TYPES.FRIEND_INVITATION]: NOTIFICATION_CATEGORIES.SOCIAL,
  [NOTIFICATION_TYPES.SOCIAL_ACTIVITY]: NOTIFICATION_CATEGORIES.SOCIAL,
  [NOTIFICATION_TYPES.NEW_BOOK]: NOTIFICATION_CATEGORIES.CONTENT,
});

export const VALID_NOTIFICATION_TYPES = new Set(Object.values(NOTIFICATION_TYPES));
export const PROMOTIONAL_CATEGORIES = new Set([NOTIFICATION_CATEGORIES.SHOP]);
