import type { ExerciseType, MovementThresholds } from './types';

const LATERAL_RAISE_THRESHOLDS: MovementThresholds = {
  minimumConfidence: 0.55,
  setupDwellFrames: 2,
  readyDwellFrames: 5,
  phaseConfirmFrames: 3,
  peakDwellFrames: 2,
  repCompleteFrames: 2,
  directionConfirmFrames: 3,
  repCooldownFrames: 14,
  maxInvalidFrames: 7,
  concentricMinFrames: 3,
  peakMinFrames: 2,
  eccentricMinFrames: 3,
  startPrimaryEnterMax: -0.18,
  startPrimaryExitMax: -0.1,
  peakPrimaryEnterMin: -0.02,
  peakPrimaryExitMin: -0.08,
  positiveVelocityEnter: 0.18,
  positiveVelocityExit: 0.1,
  negativeVelocityEnter: -0.18,
  negativeVelocityExit: -0.1,
  peakVelocityEnterAbsMax: 0.12,
  peakVelocityExitAbsMax: 0.18,
  movementMagnitudeMin: 0.14,
  setupVelocityAbsMax: 0.12,
  readySymmetryMax: 18,
  readyTorsoLeanMax: 0.12,
  minimumRom: 0.42,
  asymmetryTolerance: 24,
  torsoLeanTolerance: 0.24,
  minimumRepDurationMs: 900,
  minimumConcentricMs: 180,
  minimumPeakDurationMs: 60,
  minimumEccentricMs: 180,
  maxInvalidFrameRatio: 0.35,
  controlScoreMin: 60,
  oneArmSignalDelta: 0.18,
  controlPrimaryPenalty: 110,
  controlVelocityPenalty: 8,
};

const SHOULDER_PRESS_THRESHOLDS: MovementThresholds = {
  minimumConfidence: 0.55,
  setupDwellFrames: 2,
  readyDwellFrames: 5,
  phaseConfirmFrames: 3,
  peakDwellFrames: 2,
  repCompleteFrames: 2,
  directionConfirmFrames: 3,
  repCooldownFrames: 14,
  maxInvalidFrames: 7,
  concentricMinFrames: 3,
  peakMinFrames: 2,
  eccentricMinFrames: 3,
  startPrimaryEnterMax: 124,
  startPrimaryExitMax: 132,
  peakPrimaryEnterMin: 150,
  peakPrimaryExitMin: 144,
  positiveVelocityEnter: 14,
  positiveVelocityExit: 8,
  negativeVelocityEnter: -12,
  negativeVelocityExit: -7,
  peakVelocityEnterAbsMax: 8,
  peakVelocityExitAbsMax: 12,
  movementMagnitudeMin: 0.12,
  setupVelocityAbsMax: 6,
  readySymmetryMax: 16,
  readyTorsoLeanMax: 0.12,
  minimumRom: 24,
  asymmetryTolerance: 20,
  torsoLeanTolerance: 0.22,
  minimumRepDurationMs: 850,
  minimumConcentricMs: 160,
  minimumPeakDurationMs: 40,
  minimumEccentricMs: 160,
  maxInvalidFrameRatio: 0.35,
  controlScoreMin: 62,
  oneArmSignalDelta: 12,
  controlPrimaryPenalty: 2.2,
  controlVelocityPenalty: 6,
  startSecondaryEnterMin: -0.2,
  startSecondaryEnterMax: 0.3,
  startSecondaryExitMin: -0.28,
  startSecondaryExitMax: 0.38,
  peakSecondaryEnterMin: 0.18,
  peakSecondaryExitMin: 0.12,
};

export const MOVEMENT_THRESHOLDS: Record<ExerciseType, MovementThresholds> = {
  lateralRaise: LATERAL_RAISE_THRESHOLDS,
  shoulderPress: SHOULDER_PRESS_THRESHOLDS,
};
